version: '3.1'
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    container_name: platform_mysql
    tmpfs: /var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: publicchat_test
      MYSQL_PASSWORD: publicchat_test
      MYSQL_USER: platformuser
      MYSQL_DATABASE: publicchat_test
  redis:
    image: redis
    #container_name: cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  platform:
    build: .
    ports:
      - "7070:7070"
    depends_on:
      - mysql
      - redis
    environment:
      stream__host: redis
      admin__modKey: enableAdmin
      database__default__type: mysql
      database__default__options__database: publicchat_test
      database__default__options__host: platform_mysql
      database__default__options__username: platformuser
      database__default__options__password: publicchat_test
# ssl check
#  adnws:
#    build:
#      context: https://gitgud.io/Sapphire/Tavrn/AppDotNetWS.git


